name: Pipeline CI/CD - GitHub Pages

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  # 1. ETAPA DE CI (Integração Contínua)
  validacao-html:
    runs-on: ubuntu-latest
    steps:
    - name: Baixar Código
      uses: actions/checkout@v4

    # Validador atualizado e super rápido para a aula
    - name: Validar Estrutura do HTML
      uses: anishathalye/proof-action@v1
      with:
        directory: '.'

  # 2. ETAPA DE CD (Entrega Contínua)
  deploy-producao:
    needs: validacao-html
    runs-on: ubuntu-latest
    steps:
    - name: Baixar Código
      uses: actions/checkout@v4

    - name: Configurar o Pages
      uses: actions/configure-pages@v4

    - name: Compactar Artefatos do Site
      uses: actions/upload-pages-artifact@v3
      with:
        path: '.'

    - name: Publicar no GitHub Pages
      uses: actions/deploy-pages@v4
